name: Auto Assign to Project

on: [push]
  issues:
    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: windows-latest
    name: Assign to One Project
    steps:
    - name: Assign issues with `Bug`, 'New', 'Improve' label to project 
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: |
        contains(github.event.issue.labels.*.name, 'New') ||
        contains(github.event.issue.labels.*.name, 'Improve') ||
        contains(github.event.issue.labels.*.name, 'Bug') 
      with:
        project: 'https://github.com/Hugo-LML/tp-git-grp-6.git'
        column_name: 'To do'
